uploads = []
generated = []

[[outputs]]
id = "chY2eNsopvBl8_xZZIw5p"
uri = "file://PITCH.md"
type = "text"
title = "B.L.U.E.-J. Investor Pitch Deck"

[[outputs]]
id = "vNVb0A32X0GkPAJ9BUDXh"
uri = "file://.local/outputs/bluejgenesis-com.pdf"
type = "pdf"
title = "bluejgenesis.com.pdf"

[[outputs]]
id = "PbFZsFOtG-FW6O6snnf9D"
uri = "file://.local/outputs/bluejgenesis-com.pptx"
type = "slides"
title = "bluejgenesis.com.pptx"

[[outputs]]
id = "VZcpfwlZuVpgWhgwpJ6p8"
uri = "file://.local/outputs/B-L-U-E--J--Pitch-Deck.pdf"
type = "pdf"
title = "B.L.U.E.-J. Pitch Deck.pdf"
