import { Router, type IRouter } from "express";
import { buildSystemPrompt } from "./j-personality.js";
import { CURRICULUM } from "./curriculum.js";

const router: IRouter = Router();

router.get("/persona", (req, res) => {
  const language = String(req.query.language || "python");
  const os = String(req.query.os || "linux");
  const learnerMode = String(req.query.learnerMode || "adult-beginner") as Parameters<typeof buildSystemPrompt>[0]["learnerMode"];

  const persona = buildSystemPrompt({
    phaseIndex: 0,
    taskIndex: 0,
    currentPhase: CURRICULUM[0] ?? null,
    currentTask: CURRICULUM[0]?.tasks[0] ?? null,
    language,
    os,
    messageHistory: [],
    learnerMode,
  });

  const now = new Date().toISOString();
  const output = [
    "╔══════════════════════════════════════════════════════════════════╗",
    "║              B.L.U.E.-J. — PERSONA TRANSFER FILE                ║",
    "║        Build · Learn · Utilize · Engineer — J. Persona          ║",
    "╚══════════════════════════════════════════════════════════════════╝",
    "",
    `Generated : ${now}`,
    `Language  : ${language}`,
    `OS        : ${os}`,
    `Level     : ${learnerMode}`,
    "",
    "HOW TO USE THIS FILE",
    "────────────────────",
    "Paste the SYSTEM PROMPT section below into the 'System Prompt' or",
    "'Custom Instructions' field of any AI model:",
    "  • ChatGPT  → Settings → Personalization → Custom Instructions",
    "  • Claude   → New Project → Project Instructions",
    "  • Gemini   → Gems → Create a Gem → Instructions",
    "  • Grok     → Custom Instructions (in profile settings)",
    "  • Any API  → 'system' message field",
    "",
    "Once set, open a new conversation and the model will respond as J.",
    "",
    "══════════════════════════════════════════════════════════════════",
    "  J. SYSTEM PROMPT — PASTE EVERYTHING BELOW THIS LINE",
    "══════════════════════════════════════════════════════════════════",
    "",
    persona,
    "",
    "══════════════════════════════════════════════════════════════════",
    "  END OF PERSONA FILE — Generated by B.L.U.E.-J.",
    "══════════════════════════════════════════════════════════════════",
  ].join("\n");

  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", 'attachment; filename="j-persona.txt"');
  res.send(output);
});

export default router;
